### ISSUE TITLE
NetGAM::netGAM.df function not working

### ISSUE THREAD

**Issue by fabiodepa** [sgleich/NetGAM#1]
Hi there,
I am trying to use this package. As indicated in my dataframe I have samples in rows and ASV in columns.

Running the NetGAM::netGAM.df I get the following error:

```
> table.out <- NetGAM::netGAM.df(table.lido.w,months,days,clrt=TRUE)
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'corCAR1' in mode 'function' not found
```

Thanks for any help

**Comment by sgleich** [comment]
Hello @fabiodepa ,

Please make sure that you have the mgcv package installed and loaded. I believe this should solve the problem but if it doesn't, please let me know!

```
install.packages("mgcv")
library(mgcv)
```

**Comment by fabiodepa** [comment]
Hello @sgleich,

Thank you for your quick reply.
Your suggestion worked, thanks! For some reasons, probably due to my environment, I simply loaded the `vegan` package that has mgcv attached, for what I understood. 

**However**, now it runs for some seconds but then I get the following error:

```
Error in solve.default(-val) :
Routine Lapack dgesv: the system is exactly singular: U[2,2] = 0
```

I give you some background info about my dataset: I have 1576 ASVs across 11 samples (that are in a time series with a sampling every season for 2 years and a half).

Any idea?
Thanks

**Comment by sgleich** [comment]
Hi @fabiodepa ,

That is an error associated with the mgcv package. Usually, I find that this error occurs when the counts for a specific ASV are strange (e.g. maybe the entire column is 0s)? Perhaps we can iterate through your ASVs and find the one that is causing issues to see what the specific problem is. Let's apply the CLR transformation before applying the netGAM.df function just so we can get at the root of the problem. 

```
dfCLR <- as.data.frame(clr(table.lido.w))
gamOut <- NULL
for (asv in 1:ncol(dfCLR)){
  tmp <- dfCLR[c(asv)]
  out <- netGAM.df(tmp,months,days,clrt=FALSE)
  print("Success with ASV #")
  print(paste(asv))
  out <- out[,1]
  gamOut <- cbind(gamOut,out)
  colnames(gamOut)[asv] <- colnames(dfCLR)[asv]
}

```
If you run this loop, you should be able to pin point the specific ASV that is causing trouble. Then, we can look at the abundances of that ASV over time and see if there's a logical explanation for the error or a bug in the code. 

Sorry about the errors and confusion!

**Comment by fabiodepa** [comment]
Hi @sgleich,
Thank you for your message. I hope I am not stressing you too much :)

The loop you suggested worked and here is the suspect:

```
                 ASV1860
20181115-BLIDO-F       0
20190213-BLIDO-F       0
20190515-BLIDO-F       0
20190822-BLIDO-F     476
20191104-BLIDO-F       0
20200217-BLIDO-F       0
20200529-BLIDO-F       0
20200827-BLIDO-F      71
20201109-BLIDO-F       0
20210219-BLIDO-F       0
20210519-BLIDO-F       0
```
I see your point now, do you think it will be better to remove all those ASV with too many zeros?

Thanks

I paste here my `sessionInfo()` for completeness:

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS/LAPACK: /Users/fabio/anaconda3/lib/libmkl_rt.dylib

locale:
[1] it_IT.UTF-8/it_IT.UTF-8/it_IT.UTF-8/C/it_IT.UTF-8/it_IT.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] compositions_2.0-4 mgcv_1.8-40        nlme_3.1-159       vegan_2.5-7       
[5] lattice_0.20-45    permute_0.9-7      NetGAM_0.1         dplyr_1.0.10      
[9] phyloseq_1.36.0   

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.2       reshape2_1.4.4         purrr_0.3.4           
 [4] splines_4.1.0          rhdf5_2.36.0           colorspace_2.0-3      
 [7] vctrs_0.4.1            generics_0.1.3         stats4_4.1.0          
[10] utf8_1.2.2             survival_3.2-13        rlang_1.0.5           
[13] pillar_1.8.1           glue_1.6.2             BiocGenerics_0.38.0   
[16] GenomeInfoDbData_1.2.6 foreach_1.5.1          lifecycle_1.0.2       
[19] plyr_1.8.7             robustbase_0.95-0      stringr_1.4.0         
[22] zlibbioc_1.38.0        Biostrings_2.60.2      munsell_0.5.0         
[25] gtable_0.3.0           codetools_0.2-18       Biobase_2.52.0        
[28] IRanges_2.26.0         GenomeInfoDb_1.28.4    biomformat_1.20.0     
[31] parallel_4.1.0         fansi_1.0.3            DEoptimR_1.0-11       
[34] Rcpp_1.0.9             scales_1.2.0           S4Vectors_0.30.2      
[37] jsonlite_1.7.2         XVector_0.32.0         tensorA_0.36.2        
[40] ggplot2_3.3.6          stringi_1.7.8          grid_4.1.0            
[43] ade4_1.7-18            cli_3.4.0              tools_4.1.0           
[46] rhdf5filters_1.4.0     bitops_1.0-7           magrittr_2.0.3        
[49] RCurl_1.98-1.5         tibble_3.1.8           cluster_2.1.2         
[52] crayon_1.5.1           ape_5.5                pkgconfig_2.0.3       
[55] bayesm_3.1-4           MASS_7.3-54            Matrix_1.3-4          
[58] data.table_1.14.2      iterators_1.0.13       Rhdf5lib_1.14.2       
[61] R6_2.5.1               multtest_2.48.0        igraph_1.3.4          
[64] compiler_4.1.0
```

**Comment by sgleich** [comment]
Hi @fabiodepa ,

No stress at all! I'm happy to help. And if it's a bug with the package code, it's great for me to be aware of so I can fix it. 

Would you mind taking a look at the CLR-transformed abundances of ASV1860? The netGAM.df function seems to run fine for me on the vector of abundances you pasted above. So, I'm assuming the issue is with the CLR-transformed abundances of this specific ASV (which are the values being passed into the netGAM.df function).

In terms of removing ASVs with too many 0s, that is a personal choice that you can make for your specific networking project. There are pros and cons to removing ASVs with a high number of 0s and I don't think there is a clear "right" or "wrong" answer when it comes to ASV filtering. If you want, you can try removing ASVs with >= 9 0s and see how that alters your data frame and network output.

**Comment by fabiodepa** [comment]
Thanks @sgleich!
here are the CLR-transformed values:

```
dfCLR[,"ASV1860"]
 [1] 0.000000000 0.000000000 0.000000000 2.263381753 0.000000000 0.000000000
 [7] 0.000000000 0.001424944 0.000000000 0.000000000 0.000000000
```
To be honest there are a lot of ASVs with zeros in some samples... I would think about it maybe to scale down complexity in the network later...

**Comment by sgleich** [comment]
Hi @fabiodepa ,

This vector of CLR-transformed values worked when I ran the netGAM.df function with MOY and MCount vectors I made up based on the sampling information you provided me with (i.e. seasonal sampling over 2.5 years). I'd love to try and reproduce this error myself so I can figure out if this is a code error or some other error involving dependencies or input.  Would you mind also sharing the MOY and MCount vectors you are feeding into the netGAM.df function?

**Comment by fabiodepa** [comment]
Hi @sgleich 
Here is the table of ASV, sample names are quite clear for seasons and days but basically my MOY and MCount were:

```
months <- c(1,2,3,4,1,2,3,4,1,2,3)
days <- 1:11
```
[test_asv_table.txt](https://github.com/sgleich/NetGAM/files/9569285/test_asv_table.txt)

Thanks

**Comment by sgleich** [comment]
Hi @fabiodepa 

I think I see the issue! The 'months' vector should be months 1-12 (i.e. Jan = 1, Feb = 2, March = 3, etc.). So based on your data it should be: 

```
months <- c(11,2,5,8,11,2,5,8,11,2,5)
```

The 'days' vector should be the day of _monthly_ time-series. Since your sampling scheme skips months, you need to account for that in your 'days' vector. Based on your data, your 'days' vector should be: 

```
days <- c(1,4,7,10,13,16,19,22,25,28,31)
```

To clarify with an example, let's say the first sample of your time-series was collected in February, the second sample was collected in June, and the third sample was collected in July, your 'months' vector would be (2,6,7) and your 'days' vector would be (1,5,6)

If you replace what you have for the 'months' and 'days' vector with what I wrote out above ^ you should resolve the error!

Let me know if you have questions or if my solution does not work.

**Comment by fabiodepa** [comment]
Hi @sgleich ,
Thank you for the clarification, this was not clear to me from the example I found liked from github.
However, I still get the error:

```
Error in solve.default(-val) :
Routine Lapack dgesv: the system is exactly singular: U[2,2] = 0
```

I tried the loop you suggest and it stuck at a different ASVs from before:

```
> table.lido.w[,"ASV3089"]
OTU Table:          [1 taxa and 11 samples]
                     taxa are columns
                 ASV3089
20181115-BLIDO-F       0
20190213-BLIDO-F       0
20190515-BLIDO-F      19
20190822-BLIDO-F       0
20191104-BLIDO-F       0
20200217-BLIDO-F      19
20200529-BLIDO-F       0
20200827-BLIDO-F       0
20201109-BLIDO-F       0
20210219-BLIDO-F       0
20210519-BLIDO-F       0

> dfCLR[,"ASV3089"]
 [1]  0.000000  0.000000 -1.408619  0.000000  0.000000 -1.339730  0.000000
 [8]  0.000000  0.000000  0.000000  0.000000
```

Did it work on your system with the months and days vector you suggested?

**Comment by sgleich** [comment]
Hi @fabiodepa ,

Yes, I ran the entire ASV table you provided with the new 'months' and 'days' vectors I posted above. After running for a few minutes, the function finished up and my 'try' data frame contained the GAM-transformed ASV abundances.
```
try <- netGAM.df(df,months,days,clrt=TRUE)
```

The netGAM.df function will produce error messages like the one you pasted above as it runs sometimes because it is testing out numerous GAM formulas. Some of the GAM formulas are not good fits for the ASV abundance data, so error message appear. However, the final GAM formula that is selected for the output data frame will be a formula that does _not_ result in an error message. You'll know that an optimal GAM was selected and the program worked if you get an output in your global environment (e.g. a data frame named 'try').

Hopefully this is helpful and makes sense. Please let me know if you're still having issues getting the function to produce an output ASV table. In that case, I think there might be an issue with dependencies that we can try to address.

**Comment by fabiodepa** [comment]
Hi @sgleich,

I see!!! I did not understand that the function tests many formulas and one can get errors but it can find working solutions anyway. That was the issue I guess... Because I thought it got stuck when I saw the error messages, the function was still running but I killed it...

So as you suggested I let it go through all the errors and finally I got my data frame of transformed values!

That's great!

So issue solved I guess, I will let you know something about the output :)

Thanks again for your support!
Fabio
